stages:
  - validate
  - deploy
  - delete

.template:
  image:
    name: hashicorp/terraform:1.9.3
    entrypoint: [""]
  before_script:
    - terraform init

plan:
  extends: .template
  stage: validate
  script:
    - terraform validate
    - terraform plan -out plan.tfplan
  cache:
    key: planning
    policy: push
    paths:
      - plan.tfplan
    when: on_success

apply:
  extends: .template
  stage: deploy
  script:
    - terraform apply plan.tfplan
  cache:
    policy: pull
    key: planning
    paths:
      - plan.tfplan
  when: on_success

destroy:
  extends: .template
  stage: delete
  script:
    - terraform destroy -auto-approve
  when: manual
